[2022-06-01 20:03:29,025] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-06-01 20:03:29,029] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-05-31T00:00:00+00:00 [queued]>
[2022-06-01 20:03:29,029] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:29,030] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-01 20:03:29,030] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 20:03:29,040] {taskinstance.py:1378} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-05-31 00:00:00+00:00
[2022-06-01 20:03:29,061] {standard_task_runner.py:52} INFO - Started process 11705 to run task
[2022-06-01 20:03:29,067] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-05-31T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp793fekzu', '--error-file', '/tmp/tmpb7dqwrkb']
[2022-06-01 20:03:29,068] {standard_task_runner.py:80} INFO - Job 15: Subtask is_api_available
[2022-06-01 20:03:29,100] {task_command.py:370} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-05-31T00:00:00+00:00 [running]> on host TIGER0990.tigeranalytics.local
[2022-06-01 20:03:29,132] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-31T00:00:00+00:00
[2022-06-01 20:03:29,133] {http.py:97} INFO - Poking: api/
[2022-06-01 20:03:29,138] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-06-01 20:03:29,138] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-06-01 20:03:29,794] {base.py:301} INFO - Success criteria met. Exiting.
[2022-06-01 20:03:29,800] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220531T000000, start_date=20220601T143329, end_date=20220601T143329
[2022-06-01 20:03:29,848] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-01 20:03:29,878] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
